[package]
name = "bevy_mod_js_scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bevy = { version = "0.7.0", default-features = false }
bevy_reflect = "0.7.0"

deno_core = "0.136.0"

[dev-dependencies]
bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_winit", "x11", "filesystem_watcher"] }
