[package]
name = "bevy_js_scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.7.0"
bevy_reflect = "0.7.0"
deno_core = "0.136.0"

[dev-dependencies]
bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_winit", "x11"] }
